# Setup
title:            GDP Blog
tagline:          'Programming & Study'
description:      'Personal Blog of Miah, Md Shahjahan; Occasional Blog posts about Programming'
url:              https://smiah.dev/
baseurl:          '/'
paginate:         5
markdown: kramdown
style: kjhealy
#style: davewhipp

# About and contact
author:
  name:           'Miah, Md Shahjahan'
  url:            https://github.com/mdshahjahanmiah

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

